dryRun: false
debug: true

branches:
  - name: main

# Order matters
plugins:
  - "@semantic-release/commit-analyzer"

  - "@semantic-release/release-notes-generator"

  - "@semantic-release/changelog"

  - - "@semantic-release/exec"
    - verifyReleaseCmd: echo "new-release-version=${nextRelease.version}" >> $GITHUB_OUTPUT
      prepareCommand: |
        uv version ${nextRelease.version}
        uv sync --group docs
        make -C docs docs
      successCmd: |
        export DEBUG=rdme*
        echo "Publishing documentation to readme.io..."
        rdme docs docs/src/_build/readme-io
        echo "✅ Documentation published to readme.io"

  - - "@semantic-release/git"
    - message: 'chore(release): ${nextRelease.version} \n\n${nextRelease.notes}'
      assets:
        - CHANGELOG.md
        - pyproject.toml
        - docs/*.md

  - - "@semantic-release/github"
    - assets:
        - path: "lumos-linux-*.tar.gz"
          label: "Linux Binary"
        - path: "lumos-macos-*.tar.gz"
          label: "macOS Binary"
        - path: "lumos-windows-*.tar.gz"
          label: "Windows Binary"
