dryRun: false
debug: true

branches:
  - name: main

# Order matters
plugins:
  - "@semantic-release/commit-analyzer"

  - "@semantic-release/release-notes-generator"

  - "@semantic-release/changelog"

  - - "@semantic-release/exec"
    - verifyReleaseCmd: echo "new-release-version=${nextRelease.version}" >> $GITHUB_OUTPUT
      prepareCommand: |
        uv version ${nextRelease.version}
        uv sync --group docs
        make -C docs docs

  - - "@semantic-release/git"
    - message: 'chore(release): ${nextRelease.version} \n\n${nextRelease.notes}'
      assets:
        - CHANGELOG.md
        - pyproject.toml
        - docs/*.md

  - - "@semantic-release/github"
    - assets:
        - path: "lumos-linux-*.tar.gz"
          label: "Linux Binary"
        - path: "lumos-macos-*.tar.gz"
          label: "macOS Binary"
        - path: "lumos-windows-*.tar.gz"
          label: "Windows Binary"
        - path: "lumos-*.whl"
          label: "Python Wheel"

  - - "@qiwi/semantic-release-gh-pages-plugin"
    - src: docs/sphinx/_build/html
      msg: "docs: update documentation for ${nextRelease.version}"
