dryRun: false
debug: true

branches:
  - name: main

# Order matters
plugins:
  - "@semantic-release/commit-analyzer"

  - "@semantic-release/release-notes-generator"

  - "@semantic-release/changelog"

  - - "@semantic-release/exec"
    - verifyReleaseCmd: echo "new-release-version=${nextRelease.version}" >> $GITHUB_OUTPUT
    - prepareCommand: uv version ${nextRelease.version}

  - - "@semantic-release/git"
    - message: 'chore(release): ${nextRelease.version} \n\n${nextRelease.notes}'
      assets:
        - CHANGELOG.md
        - pyproject.toml

  - - "@semantic-release/github"
    - assets:
        - path: "lumos-*.tar.gz"
